ecommerence/ecommerence/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns,static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('store.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root= settings.MEDIA_ROOT)

ecommerence/store/urls.py
from django.urls import path
from . import views
app_name ='store'
urlpatterns = [
    path('',views.store,name='store'),
    path('cart',views.cart,name='cart'),
    path('checkout',views.checkout,name='checkout'),
    path('updateItem',views.updateItem,name='updateItem'),
    path('processOrder',views.processOrder,name='processOrder'),
]

ecommerence/store/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=200, null=True, blank=True)
    email = models.EmailField(null=True, blank=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200, null=True, blank=True)
    price = models.DecimalField(max_digits=7, decimal_places=2)
    digital = models.BooleanField(default=False)
    image = models.ImageField(upload_to="product_images", blank=True, null=True)

    def __str__(self):
        return self.name


class Order(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True
    )
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    transaction_id = models.CharField(max_length=200)

    def __str__(self):
        return str(self.id)

    @property
    def get_cart_total(self):
        order_items = self.orderitem_set.all()
        total = sum([item.get_total for item in order_items])
        return total

    @property
    def get_cart_items(self):
        order_items = self.orderitem_set.all()
        total = sum([item.quantity for item in order_items])
        return total

    @property
    def shipping(self):
        shipping = False
        orderItems = self.orderitem_set.all()
        for i in orderItems:
            if i.product.digital == False:
                shipping = True
        return shipping


class OrderItem(models.Model):
    product = models.ForeignKey(
        Product, on_delete=models.SET_NULL, blank=True, null=True
    )
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    quantity = models.IntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total


class ShippingAddress(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, blank=True, null=True
    )
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=200, null=True, blank=True)
    city = models.CharField(max_length=200, null=True, blank=True)
    state = models.CharField(max_length=200, null=True, blank=True)
    zipcode = models.CharField(max_length=200, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.address

ecommerence/store/views.py
from django.shortcuts import render
from .models import *
from django.http import JsonResponse
import json, datetime
from .utils import cookieCart, cartData, guestOrder


# Create your views here.
def store(request):
    data = cartData(request)
    cartItems = data["cartItems"]

    products = Product.objects.all()
    context = {"products": products, "cartItems": cartItems}
    return render(request, "store/store.html", context)


def cart(request):
    data = cartData(request)
    cartItems = data["cartItems"]
    order = data["order"]
    items = data["items"]

    context = {"items": items, "order": order, "cartItems": cartItems}
    return render(request, "store/cart.html", context)


def checkout(request):
    data = cartData(request)
    cartItems = data["cartItems"]
    order = data["order"]
    items = data["items"]

    context = {"items": items, "order": order, "cartItems": cartItems}
    return render(request, "store/checkout.html", context)


def updateItem(request):
    data = json.loads(request.body)
    productId = data["productId"]
    action = data["action"]

    print("Action", action)
    print("ProductId", productId)

    customer = request.user.customer
    product = Product.objects.get(id=productId)
    order, created = Order.objects.get_or_create(customer=customer, complete=False)

    orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

    if action == "add":
        orderItem.quantity = orderItem.quantity + 1
    elif action == "remove":
        orderItem.quantity = orderItem.quantity - 1

    orderItem.save()

    if orderItem.quantity <= 0:
        orderItem.delete()
    return JsonResponse("Item is Added", safe=False)


def processOrder(request):
    transcation_id = datetime.datetime.now().timestamp()
    data = json.loads(request.body)
    if request.user.is_authenticated:
        customer = request.user.customer
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

    else:
        customer, order = guestOrder(request, data)
    total = float(data["form"]["total"])
    order.transaction_id = transcation_id

    if total == order.get_cart_total:
        order.complete = True
    order.save()

    if order.shipping == True:
        ShippingAddress.objects.create(
            customer=customer,
            order=order,
            address=data["shipping"]["address"],
            city=data["shipping"]["city"],
            state=data["shipping"]["state"],
            zipcode=data["shipping"]["zipcode"],
        )

    print("Data; ", request.body)
    return JsonResponse("Purchased Item...", safe=False)

ecommerence/templates/store/cart.html
{%extends 'store/main.html'%}
{% load static %}
{%block body%}
<div class="row">
    <div class="col-lg-12">

        <div class="box-element">
            <a class="btn btn-outline-dark" href="{%url 'store:store'%}">&#8592;Continue Shopping</a>

            <br>

            <table class="table">
                <tr>

                    <th>
                        <h5>Items: <strong>{{order.get_cart_items}}</strong></h5>
                    </th>
                    <th>
                        <h5>Total: <strong>${{order.get_cart_total|floatformat:2}}</strong></h5>
                    </th>
                    <th>
                        <a href="{%url 'store:checkout'%}" class="btn btn-success"
                            style="float: right; margin: 5px;">Checkoout</a>
                    </th>
                </tr>
            </table>
        </div>

        <br>

        <div class="box-element">
            <div class="cart-row">
                <div style="flex: 2;"></div>
                <div style="flex: 2;"><strong>Item</strong></div>
                <div style="flex: 1;"><strong>Price</strong></div>
                <div style="flex: 1;"><strong>Quantity</strong></div>
                <div style="flex: 1;"><strong>Total</strong></div>
            </div>

            {%for item in items%}
            <div class="cart-row">
                <div style="flex: 2;"><img class="row-image" src="{{item.product.image.url}}" alt=""></div>
                <div style="flex: 2;">{{item.product.name}}</div>
                <div style="flex: 1;">${{item.product.price|floatformat:2}}</div>
                <div style="flex: 1;">
                    <p class="quantity">{{item.quantity}}</p>
                    <div class="quantity">
                        <img class="chg-quantity update-cart" data-product="{{item.product.id}}" data-action="add"
                            src="{%static 'images/arrow-up.png'%}" alt="">
                        <img class="chg-quantity update-cart" data-product="{{item.product.id}}" data-action="remove"
                            src="{%static 'images/arrow-down.png'%}" alt="">
                    </div>
                </div>
                <div style="flex: 1;">${{item.get_total}}</div>
            </div>
            {%endfor%}
        </div>

    </div>
</div>
{%endblock%}

ecommerence/templates/store/checkout.html
{%extends 'store/main.html'%}
{% load static %}
{%block body%}
<div class="row">
    <div class="col-lg-6">
        <div class="box-element" id="form-wrapper">
            <form id="form">
                <div id="user-info">
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email..">
                    </div>
                </div>

                <div id="shipping-info">
                    <hr>
                    <p>Shipping Information:</p>
                    <hr>
                    <div class="form-field">
                        <input class="form-control" type="text" name="address" placeholder="Address..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="city" placeholder="City..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="state" placeholder="State..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="country" placeholder="Zip code..">
                    </div>
                </div>

                <hr>
                <input id="form-button" class="btn btn-success btn-block" type="submit" value="Continue">
            </form>
        </div>

        <br>
        <div class="box-element hidden" id="payment-info">
            <small>Paypal Options</small>
            <button id="make-payment">Make Payment</button>
        </div>

    </div>

    <div class="col-lg-6">
        <div class="box-element">
            <a class="btn btn-outline-dark" href="{% url 'store:cart' %}">&#x2190; Back to Cart</a>
            <hr>
            <h3>Order Summary</h3>
            <hr>
            {%for item in items%}
            <div class="cart-row">
                <div style="flex:2"><img class="row-image" src="{{item.product.image.url}}"></div>
                <div style="flex:2">
                    <p>{{item.product.name}}</p>
                </div>
                <div style="flex:1">
                    <p>${{item.product.price|floatformat:2}}</p>
                </div>
                <div style="flex:1">
                    <p>x{{item.quantity}}</p>
                </div>
            </div>
            {%endfor%}

            <h5>Items: {{order.get_cart_items}}</h5>
            <h5>Total: ${{order.get_cart_total|floatformat:2}}</h5>
        </div>
    </div>
</div>

<script type="text/javascript">
    var shipping = '{{order.shipping}}'
    var total = '{{order.get_cart_total}}'

    if (shipping == 'False') {
        document.getElementById('shipping-info').innerHTML = ''
    }

    if (user != 'AnonymousUser') {
        document.getElementById('user-info').innerHTML = ''
    }

    if (shipping == 'False ' && user != 'AnonymousUser') {
        //Hide Entire Form if user is logged in and shipping in false
        document.getElementById('form-wrapper').classList.add('hidden')
        //Show payment if already logged in user wants to buy an item that does not require shipping
        document.getElementById('payment-info').classList.remove('hidden')

    }

    var form = document.getElementById('form')

    form.addEventListener('submit', function (e) {
        e.preventDefault()
        console.log('Form is submitted....')
        document.getElementById('form-button').classList.add('hidden')
        document.getElementById('payment-info').classList.remove('hidden')

    })

    document.getElementById('make-payment').addEventListener('click', function (e) {
        submitFormData()
    })

    function submitFormData() {
        console.log('Payment Button Clicked....')

        var userformdata = {
            'name': null,
            'email': null,
            'total': total,
        }

        var shippingInfo = {
            'address': null,
            'city': null,
            'state': null,
            'zipcode': null,
        }

        if (shipping != 'False') {
            shippingInfo.address = form.address.value
            shippingInfo.city = form.city.value
            shippingInfo.state = form.state.value
            shippingInfo.zipcode = form.zipcode.value
        }


        if (user === 'AnonymousUser') {
            userformdata.name = form.name.value
            userformdata.email = form.email.value
        }

        var url = '/processOrder'
        fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify({
                'form': userformdata, 'shipping': shippingInfo
            })

        })

            .then((response) => response.json())
            .then((data) => {
                console.log('Sucess:', data);
                alert('Transcation Completed!');

                cart = {}
                document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
                window.location.href = "{%url 'store:store'%}"
            })
    }
</script>
{%endblock%}

ecommerence/templates/store/main.html
<!DOCTYPE html>
{%load static%}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>E-Commerence</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <link rel="stylesheet" href="{%static 'css/main.css'%}">
    <script type="text/javascript">
        var user = '{{request.user}}'
        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        const csrftoken = getToken('csrftoken');
        function getCookie(name) {
            var cookieArr = document.cookie.split(";")

            for (var i = 0; i < cookieArr.length; i++) {
                var cookiePair = cookieArr[i].split("=");

                if (name === cookiePair[0].trim()) {
                    return decodeURIComponent(cookiePair[1]);
                }
            }
            return null
        }

        var cart = JSON.parse(getCookie('cart'));
        if (cart == undefined) {
            cart = {}
            console.log('Cart was Created!')
            document.cookie = 'cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }

    </script>
</head>

<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary bg-dark  navbar bg-dark" data-bs-theme="dark">
        <div class=" container-fluid">
            <a class="navbar-brand" href="{%url 'store:store'%}">E-Comm</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{%url 'store:store'%}">Store</a>
                    </li>
                </ul>

                <div class="form-inline my-2 my-lg-0">
                    <a href="#" class="btn btn-warning">Login</a>

                    <a href="{%url 'store:cart'%}">
                        <img id="cart-icon" src="{% static 'images/cart.png' %}">
                    </a>
                    <p id="cart-total">{{cartItems}}</p>

                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        {%block body%} {%endblock body%}
    </div>




    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.7/dist/umd/popper.min.js"
        integrity="sha384-zYPOMqeu1DAVkHiLqWBUTcbYfZ8osu1Nd6Z89ify25QV9guujx43ITvfi12/QExE"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.min.js"
        integrity="sha384-Y4oOpwW3duJdCWv5ly8SCFYWqFDsfob/3GkgExXKV4idmbt98QcxXYs9UoXAB7BZ"
        crossorigin="anonymous"></script>
    <script type="text/javascript" src="{%static 'js/cart.js'%}"></script>
</body>

</html>

ecommerence/templates/store/store.html
{%extends 'store/main.html'%}
{%load static%}
{%block body%}
<div class="row">
    {%for product in products%}
    <div class="col-lg-4">
        {% if product.image %}
        <img class="thumbnail" src="{{product.image.url}}">
        {% else %}
        <img class="thumbnail" src="{% static 'images/placeholder.png' %}">
        {% endif %}
        <div class="box-element product">
            <h6><strong>{{product.name}}</strong></h6>
            <hr>
            <button data-product="{{product.id}}" data-action="add"
                class="btn btn-outline-secondary add-btn update-cart">Add to
                Cart</button>
            <a href="" class="btn btn-outline-success">View</a>
            <h4 style="display: inline-block; float: right">${{product.price|floatformat:2}}</h4>
        </div>
    </div>
    {%endfor%}
</div>
{%endblock%}